export const dummyTeamData = [
  {
    productName: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    desc: 'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    vendor: { name: 'Vendor C', detailRef: '62448847b9716d492ed0ba3d' },
    category: 'electronics',
    originalPrice: 49.99,
    teamDiscountedPrice: 39.99,
    maxQtyPerCustomer: 10,
    totalTeamSize: 10,
    totalTeamRound: 4,
    teamDurationInDays: 3,
    teamDealStartedAt: Date.now() + 5000,
    reviewsCount: 5,
    averageRating: 3.4,
    currentTeamSize: 0,
    currency: 'CAD',
  },
  {
    productName: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    desc: 'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    vendor: { name: 'Vendor A', detailRef: '624488622a32caef759c27f7' },
    category: 'electronics',
    originalPrice: 129.99,
    teamDiscountedPrice: 99.99,
    maxQtyPerCustomer: 5,
    totalTeamSize: 4,
    totalTeamRound: 4,
    teamDurationInDays: 3,
    teamDealStartedAt: Date.now() + 5000,
    reviewsCount: 2,
    averageRating: 5,
    currentTeamSize: 0,
    currency: 'CAD',
  },
  {
    productName: 'Airpods Wireless Bluetooth',
    image: '/images/airpods.jpg',
    desc: 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    vendor: { name: 'Vendor A', detailRef: '624488622a32caef759c27f7' },
    category: 'electronics',
    originalPrice: 89.99,
    teamDiscountedPrice: 69.99,
    maxQtyPerCustomer: 6,
    totalTeamSize: 10,
    totalTeamRound: 3,
    teamDurationInDays: 5,
    teamDealStartedAt: Date.now() + 5000,
    reviewsCount: 15,
    averageRating: 3,
    currentTeamSize: 0,
    currency: 'CAD',
  },
  {
    productName: 'IPhone 13 Pro 256GB Memory',
    image: '/images/phone.jpg',
    desc: 'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    vendor: { name: 'Vendor B', detailRef: '62448871afb4876e5deb2ee4' },
    category: 'electronics',
    originalPrice: 1099.99,
    teamDiscountedPrice: 899.99,
    maxQtyPerCustomer: 3,
    totalTeamSize: 3,
    totalTeamRound: 2,
    teamDurationInDays: 5,
    teamDealStartedAt: Date.now() + 5000,
    reviewsCount: 5,
    averageRating: 3.4,
    currentTeamSize: 0,
    currency: 'CAD',
  },
  {
    productName: 'Sony PlayStation 5 Pro White',
    image: '/images/playstation.jpg',
    desc: 'Get a better handle on your games with this NEW SONY PS STATION FOR ULTIMATE EXPEREINCES',
    vendor: { name: 'Vendor C', detailRef: '62448847b9716d492ed0ba3d' },
    category: 'entertainment',
    originalPrice: 399.99,
    teamDiscountedPrice: 319.99,
    maxQtyPerCustomer: 6,
    totalTeamSize: 4,
    totalTeamRound: 3,
    teamDurationInDays: 6,
    teamDealStartedAt: Date.now() + 5000,
    reviewsCount: 8,
    averageRating: 2.4,
    currentTeamSize: 0,
    currency: 'CAD',
  },
];

// console.log(dummyTeamData.length);
